// Mocks generated by Mockito 5.4.4 from annotations
// in chatflutter/test/providers/list_message_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:chatflutter/deps/dependance.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [Dependance].
///
/// See the documentation for Mockito's code generation for more information.
class MockDependance extends _i1.Mock implements _i2.Dependance {
  MockDependance() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int doubler(int? a) => (super.noSuchMethod(
        Invocation.method(
          #doubler,
          [a],
        ),
        returnValue: 0,
      ) as int);

  @override
  int additionner(int? a) => (super.noSuchMethod(
        Invocation.method(
          #additionner,
          [a],
        ),
        returnValue: 0,
      ) as int);
}
